plugins:
  - jekyll-feed
title: Michał Łępicki
description: a weblog
url: https://blog.michallepicki.com
author: Michał Łępicki
exclude: ["Gemfile", "Gemfile.lock", "README.md", "run.sh"]
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      author: Michał Łępicki
      layout: page
  # -
  #   scope:
  #     path: "" # an empty string here means all files in the project
  #     type: pages
  #   values:
  # -
  #   scope:
  #     path: "" # an empty string here means all files in the project
  #     type: posts
  #   values:

# title for posts is the slug value, which by default comes from the hyphenated file name
# (not from title value). This setting only affects collections like posts, not pages.
permalink: /:title:output_ext # make posts urls behave like pages urls
highlighter: rouge
sass:
  style: compressed
titles_from_headings:
  enabled: false
compress_html:
  clippings: all
  comments: all
  endings: []
  ignore:
    envs: []
  blanklines: false
  profile: false
  startings: []
